export const LOAD_GRAPH_SUCCESS = 'LOAD_GRAPH_SUCCESS';
export const INITIALIZE_NETWORK_SUCCESS = 'INITIALIZE_NETWORK_SUCCESS';
export const ADD_NODE_SUCCESS = 'ADD_NODE_SUCCESS';
export const SELECT_NOTHING = 'SELECT_NOTHING';
export const SELECT_NETWORK = 'SELECT_NETWORK';
export const SELECT_NODE = 'SELECT_NODE';
export const EDIT_NODE = 'EDIT_NODE';
